Fix button event listeners and hide keyboard when not in use
Gullskatten/beardblaster pull request #30
Opened 2021-03-20 20:49 UTC by cherrybeans

Fixes #23, Fixes #29

2021-03-20 21:31 UTC, Gullskatten requested changes
All-in-all, godt jobbet! Jeg bare la inn et par kommentarer, men disse kan egentlig resolves ganske raskt dersom du ikke er enig!

2021-03-20 21:31 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/utils/AbstractScreen.kt
> +package no.ntnu.beardblaster.utils
TLDR; Kan ikke denne flyttes til `../views/` siden alle Screens implementerer denne klassen? (kanskje endre package-name `views` til `screen`?). 

Det er heller ingen tradisjonelle "utils" i utils-packagen. I hvert fall Java-utils har ingen public constructor og "kun" statiske metoder tilgjengelige (slik som `Arrays.asList(...)`). 🤠 

Note på utils-regel fra sonatype: https://rules.sonarsource.com/java/tag/design/RSPEC-1118

2021-03-20 21:31 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/BeardBlasterGame.kt
> +            UserAuth().signIn("beard@blaster.com", "beardblaster")
Denne bør ikke med til `main`-branchen.

2021-03-20 21:31 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/utils/AbstractScreen.kt
> +) : KtxScreen, IBeardBlasterScreen {
Nå må alle screens override "setBtnEventListeners" selv om de ikke implementerer noen knapper. 
Et forslag er at man heller selv implementerer dette interfacet dersom man behøver buttonlisteners.

Kanskje kalle interfacet `ButtonEventListener`? 


Klassen for LoginScreen ville sett slik ut:

```java

class GameplayScreen(game: BeardBlasterGame) : AbstractScreen(game), ButtonEventListener { 
 // class-impl
 }
```

2021-03-20 21:34 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/utils/AbstractScreen.kt
> +) : KtxScreen, IBeardBlasterScreen {
er egentlig litt usikker på hvor god den metoden der er heller - man må liksom uansett implementere et interface som gir deg én metode, som du selv også må kalle på..

2021-03-20 22:07 UTC, einaru commented on core/src/main/kotlin/no/ntnu/beardblaster/utils/AbstractScreen.kt
> +package no.ntnu.beardblaster.utils
Støtter at `AbstractScreen` kan flyttes til `views` pakken, som godt kan endre navn til `screen`.  👍🏻

2021-03-21 19:17 UTC, Gullskatten approved these changes

2021-03-21 19:18 UTC, merged