Add GameRepository, Implement phases in-game
Gullskatten/beardblaster pull request #57
Opened 2021-04-14 21:28 UTC by cherrybeans

* Monster-commit since I was in too-deep to separate it later
* Add firestore communication for when in-game
* Switch between phases (big changes to avoid buttons etc stopping working)
* Clean up redundancy
* Add optional hook to base screen to support setting up and adding components to stage correctly (otherwise they stop working after the first phase-shift). Only an apparent problem when we start adding a lot of components like in the gameplay screen. Initializing components should only be done ONCE for correct behaviour.

Progress on #46

2021-04-15 06:44 UTC, Gullskatten approved these changes

2021-04-15 06:44 UTC, Gullskatten commented on android/src/main/kotlin/no/ntnu/beardblaster/GameRepository.kt
> +                    offer(State.Failed<Game>("The lobby has been deleted."))
The game has been deleted? 🥇

2021-04-15 06:44 UTC, Gullskatten commented on android/src/main/kotlin/no/ntnu/beardblaster/LobbyRepository.kt
> +                    "endedAt", LocalDateTime.now(ZoneOffset.UTC)
Kan godt godta denne navneendringen! 

Bakgrunnen for denne var at når `(game.ended != null)` så er kampen slutt, selv om jeg er litt usikker på om den er i aktivt bruk p.t.

2021-04-15 06:44 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/game/GameData.kt
> +        GameRepository().subscribeToGameUpdates(id).collect {
TL;DR: Det er noe bøll med subscriptions i Singletons, de avsluttes aldri (fordi singletons lever gjennom hele livssyklusen til appen).


Dette tror jeg rett og slett bør inn i Screen-klassen, eller legges ut som en egen klasse. F.eks, "GameSubscription" som kun inneholder denne metoden og blir instansiert i Screen-klassen (eller der det er behov for den).

2021-04-15 06:44 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/game/GameData.kt
> +        GameRepository().subscribeToGameUpdates(id).collect {
Tror man kan verifisere at det er noe bøll ved å logge ut etter at man har startet et spill. Da vil streamen antageligvis gi en "insufficient permission" (siden bruker-auth ikke finnes lenger).

2021-04-15 06:44 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/lobby/LobbyHandler.kt
> -        return null;
Godt det blir ryddet opp litt her...

2021-04-15 06:44 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/screen/GameplayScreen.kt
> +    private var canDo = false // TODO: To be removed when things come together properly
Skjønner ikke helt navngivingen her til `canDo`. Men forstår det slik at game over kun skal "trigges" én gang.

2021-04-15 06:44 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/ui/Elements.kt
> +fun smallBodyLabel(text: String, labelStyle: String = LabelStyle.Body.name): Label {
Endre heller den originale "body" med variabel font-scale?

```suggestion
fun bodyLabel(text: String, labelStyle: String = LabelStyle.Body.name, fontScale: Float  = 1.5f): Label {
 return scene2d.label(text, labelStyle) {
        setAlignment(Align.center)
        setFontScale(fontScale)
    }
}
```

2021-04-15 06:54 UTC, Gullskatten commented
Jeg approvet først, men lurt at vi FØRST får inn GameSubscription-klassen, slik at vi ikke innfører "logout"-buggen i main-branchen.

2021-04-15 07:04 UTC, Gullskatten requested changes

2021-04-15 07:04 UTC, Gullskatten commented on core/src/main/kotlin/no/ntnu/beardblaster/screen/MenuScreen.kt
> +    override fun update(delta: Float) {
1. Dette fører til at brukeren blir møtt med en "sort skjerm" når man går fra `LoginScreen -> MenuScreen`. 
2. `update(delta: Float)`  kalt 2 ganger hvor `UserData.instance.user == null && !UserData.instance.isLoading` er `true` (på min emulator).

2021-04-15 16:39 UTC, Gullskatten approved these changes

2021-04-15 16:39 UTC, Gullskatten commented
Closes #58

2021-04-15 16:40 UTC, Gullskatten commented
Fikset endringene jeg foreslo, er litt avhengig av at denne blir merget slik at jeg kan begynne med noe nytt for "game"-funksjonaliteten! 🤓 Merger!

2021-04-15 16:41 UTC, merged

2021-04-16 08:07 UTC, cherrybeans commented
@Gullskatten Ah wow, chill, skulle akkurat til å fikse de. Bra jobba!